apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    env: qa
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: nginx
          image: nginx
