apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        env: qa
    spec:
      containers:
        - name: nginx
          image: nginx
  selector:
    matchLabels:
      env: qa
